export const employees = [
  {
    name: 'Аин Татьяна Александровна',
    title: '  Руководитель Холдинга',
    email: 'aiN@rhana.ru',
    phone: '(910) 469-95-00',
    extNumber: '104'
  },
  {
    name: 'Акимов Сергей Викторович',
    title: 'Охранник, контролер',
    email: 'akimov@rhana-opt.ru',
    phone: '(967) 252-60-84',
    extNumber: '151'
  },
  {
    name: 'Алексеева Наталья Викторовна',
    title: 'Главный бухгалтер  "Плацента Фарм"',
    email: 'alekseeva@rhanaopt.ru',
    phone: '(916) 914-06-76',
    extNumber: '114'
  },
  {
    name: 'Бабаева Ирина Викторовна',
    title: 'Координатор специальных проектов',
    email: 'babaeva@rhana-opt.ru',
    phone: '(916) 950-12-43',
    extNumber: '156'
  },
  {
    name: 'Баталова Анжелла Максимовна',
    title: 'Маркетинг-менеджер  Лаеннек',
    email: 'batalova@rhana-opt.ru',
    phone: '(962) 917-75-00',
    extNumber: '140'
  },
  { name: 'Бойцова Надежда Александровна', title: 'Аптека  RHANA    "OOO ЭстетикПрофи" ', email: 'bojcova@rhanaopt.ru', phone: '(495) 690-24-79  (967) 015-69-25  ', extNumber: '440' },
  { name: 'Брянцева Ольга Евгеньевна', title: 'Руководитель УМЦ, директор департамента научного маркетинга', email: 'bryanceva@rhana-opt.ru', phone: '(926) 898-83-50', extNumber: '144' },
  { name: 'Валиновская Марина Рэмировна', title: 'Экономист ', email: 'valinovskaya@rhana-opt.ru', phone: '(925) 050-18-92', extNumber: '115' },
  { name: 'Вербицкая Надежда Петровна', title: 'Руководитель транспортного отдела', email: 'moro017@yandex.ru', phone: '(985) 773-70-45', extNumber: '' },
  { name: 'Воронович Сергей Николаевич', title: 'Руководитель направления интернет маркетинга', email: 'voronovich@rhana.ru', phone: '(919) 107-85-16', extNumber: '158' },
  { name: 'Ганжуева Диана Усеновна', title: 'Секретарь ресепшн ', email: 'secretary@rhana.ru', phone: '977 - 446-46-39', extNumber: '111/ 121' },
  { name: 'Герасимов Александр Евгеньевич      ', title: 'Руководитель отдела  по работе с VIP клиентами и франшизе ', email: 'gerasimov@rhanaopt.ru', phone: '(916) 545-92-65', extNumber: '130' },
  { name: 'Герман Олег  Юрьевич', title: 'Дизайнер', email: 'design@rhana.ru', phone: '(926) 001-39-50', extNumber: '123' },
  { name: 'Гришина Ирина Васильевна', title: 'Генеральный директор "ПФ", Руководитель отдела финансов', email: 'grishina@rhana.ru', phone: '(903) 505-67-00', extNumber: '110' },
  { name: 'Дивлячий Андрей Васильевич', title: 'Бренд-менеджер  Curacen ', email: 'a.divlyachiy@rhanaopt.ru', phone: '(926) 952-76-64', extNumber: '142' },
  { name: 'Дмитриева Анастасия Андреевна', title: 'Главный бухгалтер ООО "Рана Фарм"', email: 'accountab@rhana.ru', phone: '(906) 741-29-27', extNumber: '' },
  { name: 'Дмитриева Марина Кимовна', title: 'Главный бухгалтер Холдинга', email: 'accountmk@rhana.ru  ', phone: '(906) 055-37-14', extNumber: '' },
  { name: 'Дибров Алексей Борисович ', title: 'Заместитель руководителя отдела логистики и складского учета ', email: '9260119601@mail.ru', phone: '+7 (926) 011-96-01 ', extNumber: '439' },
  { name: 'Егорова Светлана Анатольевна', title: 'Руководитель отдела логистики', email: 'dumka13@yandex.ru', phone: '(963) 782-61-65', extNumber: '439' },
  { name: 'Елина Яна Викторовна', title: 'Специалист по сертификации', email: 'yanae@rhana.ru', phone: '(925) 117-72-70', extNumber: '145' },
  { name: 'Елисеева Ирина Ивановна', title: 'Менеджер по работе с дистрибуторами и АС ', email: 'eliseeva@rhanaopt.ru', phone: '(916) 587-02-54', extNumber: '134' },
  { name: 'Житникова Марина Владимировна', title: 'Помощник Президента Компании', email: 'office@rhana.ru', phone: '(985) 360-79-23', extNumber: '101' },
  { name: 'Зверев Евгений Константинович ', title: 'Специалист по учету ТМЦ', email: 'zverev1994zverev@list.ru ', phone: '(929)677-69-23', extNumber: '439' },
  { name: 'Зверева Ольга Николаевна', title: 'Директор по фин.-адм. Вопросам, операционный директор ', email: 'finance@rhana.ru', phone: '(903) 143-20-20', extNumber: '109' },
  { name: 'Иноземцева Анастасия Анатольевна ', title: 'Менеджер по работе с ключевыми клиентами', email: 'inozemceva@rhanaopt.ru', phone: '(965) 157-00-90  ', extNumber: '141' },
  { name: 'Каримова Илана Металовна', title: 'Руководитель  департамента ', email: 'karimova@rhanaopt.ru', phone: '(906) 771-26-67', extNumber: '125' },
  { name: 'Карпова Ирина Анатольевна', title: 'Руководитель направления по работе с дистрибуторами и аптечными сетями ', email: 'karpova@rhana-opt.ru', phone: '(903) 549-36-28', extNumber: '153' },
  { name: 'Качан Юлия Александровна', title: 'Руководитель  отдела кадров', email: 'kachan@rhana-opt.ru', phone: '(905) 768-09-01', extNumber: '159' },
  { name: 'Клименко Людмила Николаевна', title: 'Pr & Event менеджер ', email: 'klimenko@rhana-opt.ru ', phone: '(963) 648-19-09', extNumber: '120' },
  { name: 'Климов Дмитрий Владимирович', title: 'Системный администратор ', email: 'dmn001@mail.ru', phone: '(905) 513- 55- 66', extNumber: '' },
  { name: 'Козлов Иван Викторович', title: 'Pr - директор Клиник', email: 'prclinic@rhana.ru', phone: '8 925 825 71 76', extNumber: '157' },
  { name: 'Колотило Елена Николаевна', title: 'Pr -директор Корпорации ', email: 'pr1@rhana.ru', phone: '(903) 227-30-06', extNumber: '127' },
  { name: 'Кораблева Ирина Львовна ', title: 'Ассистент руководителя по связям с общественностью ', email: 'korableva@rhana-opt.ru', phone: '(985)  723 - 12-84', extNumber: '123' },
  { name: 'Костырина Валентина Васильевна', title: 'Зав. складом', email: 'kostyrina@rhanaopt.ru', phone: '(926) 659-91-37', extNumber: '439' },
  { name: 'Кудеев Сергей Вячеславович', title: 'Водитель Дибровой Е. А', email: '', phone: '                 (903) 222-67-77', extNumber: '' },
  { name: 'Кудрявцев Михаил Александрович ', title: 'Руководитель отдела информационных технологий ', email: '            kma@rhana-opt.ru', phone: '(999) 802-14-85', extNumber: '106' },
  { name: 'Кулигин Андрей Анатольевич', title: 'Директор по юридическим вопросам ', email: 'chief@rhana.ru', phone: '(916) 337-86-79', extNumber: '116' },
  { name: 'Левашкевич Дмитрий Анатольевич', title: 'Водитель - экспедитор/склад ', email: '', phone: '(906) 789-49-15', extNumber: '' },
  { name: 'Левашкевич Наталья Петровна', title: 'Генеральный директор МК "РАНА", Юрист', email: 'lnp@rhana.ru', phone: '(909) 646-01-46', extNumber: '108' },
  { name: 'Лошакова Оксана Васильевна ', title: 'Региональный менеджер Москва и МО', email: 'loshakova@rhana-opt.ru ', phone: '(916) 311-60-13', extNumber: '154' },
  { name: 'Макушняк Анастасия Федоровна', title: 'Методист УМЦ', email: 'metodist@rhanaopt.ru', phone: '(926) 590-16-38', extNumber: '126' },
  { name: 'Надеждина Ирина Николаевна', title: 'Заместитель главного бухгалтера ', email: 'nadezhdina@rhana-opt.ru', phone: '(903) 537-40-66', extNumber: '113' },
  { name: 'Неровнов Андрей Михайлович ', title: 'Менеджер по сопровождению продаж ', email: 'nerovnov@rhana-opt.ru', phone: '(901) 750-47-16', extNumber: '147' },
  { name: 'Неровнова Любовь Васильевна', title: 'Менеджер по продажам ', email: 'l.nerovnova@rhanaopt.ru', phone: '                 (926) 490-44-31', extNumber: '133' },
  { name: 'Новокрещенова Елена Викторовна', title: 'Менеджер по сопровождению продаж ', email: 'novokreschenova@rhana-opt.ru ', phone: '(916)511-47-25', extNumber: '137' },
  { name: 'Петрухина Екатерина Николаевна', title: 'Менеджер по поддержке продаж', email: 'petruhina@rhana-opt.ru', phone: '(962) 991-33-84', extNumber: '132' },
  { name: 'Полянская Татьяна Юрьевна', title: 'Ген. директор "Рана Фарм", менеджер по сертификации', email: 'polyanskaya@rhana.ru', phone: '                 (926) 392-38-64', extNumber: '112' },
  { name: 'Ростомян Эрна Дживановна', title: '', email: 'rastomyan@rhana-opt.ru', phone: '(925) 007-87-31', extNumber: '253' },
  { name: 'Самохина Мария Владимировна', title: 'Дизайнер', email: 'maria@rhanaopt.ru', phone: '(906) 037 -18-08', extNumber: '118' },
  { name: 'Саркисян Кристина Вагановна', title: 'Руководитель интернет - проектов', email: 'sarkisyan@rhana.ru', phone: '(915) 452-43-35', extNumber: '136' },
  { name: 'Селикатов Андрей Валерьевич ', title: 'Руководитель АХЧ', email: 'selikatov@rhana.ru', phone: '(926) 276-24-44', extNumber: '' },
  { name: 'Сергеева Ксения Федоровна', title: 'Руководитель проекта "Франшиза"', email: 'sergeeva@rhana-opt.ru', phone: '(968) 370 10 67', extNumber: '152' }, 
  { 
    name: 'Сорочьев Сергей Александрович', 
    title: 'Руководитель по развитию косметологических люксовых брендов ', 
    email: 'sorochev@rhana-opt.ru', 
    phone: '(906) 085-82-86', 
    extNumber: '117' },
  { name: 'Степанова Юлиана Петровна', title: 'Менеджер по продажам ', email: 'stepanova@rhanaopt.ru', phone: '(977) 255-86-76', extNumber: '128' },
  { name: 'Стома Лариса Игоревна', title: 'Главный врач мед. Корпорации Рана', email: 'stoma@rhana.ru ', phone: '(916) 528-22-84', extNumber: '139' },
  { name: 'Тараева Яна Витальевна', title: 'Менеджер по продажам ', email: 'taraeva@rhanaopt.ru', phone: '(903) 744-94-55', extNumber: '138' },
  { name: 'Туманян Карина Владимировна', title: 'Медицинский директор', email: 'tumanian@rhana.ru', phone: '(910) 000-98-46', extNumber: '148' },
  { name: 'Шарапова Светлана Анатольевна', title: 'Руководитель отдела прямых продаж ', email: 'sharapova@rhanaopt.ru', phone: '(916) 249-49-74', extNumber: '131' },
  { name: 'Элоян Виктория Камовна', title: 'Бухгалтер ', email: 'viktoria-buh@rhana.ru ', phone: '(968) 608-91-81', extNumber: '107' },
  { name: 'Элоян Камо Арменакович', title: 'Водитель -офис - Клиники ', email: '', phone: '(906) 763-45-50', extNumber: '' },
  { name: 'Юрлова Александра Юрьевна', title: 'Бренд-менеджер  косметика ', email: 'jurlova@rhanaopt.ru', phone: '(910) 472-69-12', extNumber: '122' }
];